mañana terminar todo lo posible
y hacer los de la guia 2 que te mostro la chica


jueves ver la clase grabada de las series 
tambien ver solucion de mica que no ví sobre "dos cadenas y la tercera tiene la combinacion de esto, eje5.st"

sabado hacer todos los modelos de examenes. y repaso
lunes a la mañana modelos de examen y repaso


HACER REPASOS FUERTES EN LA MAÑANAA PORQUE EN LA NOCHE NO LOS HAGO NUNCA. 
HACERSE PREGUNTAS DE 
COMO RESOLVERIAS ESTO?
Y ESTO COMO RESOLVERIAS? 
ESO AYUDA MUCHO

PARCIAL CON HOJA Y PAPEL ASI QUE VIERNES HACER LOS MODELOS DE EXAMENES CON HOJA Y LAPIZ SI O SI