metodo_clase.st
"Para trabajar con metodo de clase es igual de sencillo que con metodo de instancia"


"Recordar que los metodos se crean de manera directa si uno quiere, no hace falta variable de instancias(depende la situacion)"
"Solo se necesita variable de instancia para los metodos en los setters y los getters"

"Solo ingresar en la clase"

elegir "class side"

luego te sale el mismo mensaje que el metodo de instancia

yo cree este metodo/mensaje

hola
	^ 'hola'


en el Playground se ejecuta

NombreDeLaClase mensaje.

ejemplo

TrabajarConClase hola.

devuelve 'hola'

Hay una foto que puse en la carpeta principal.
