pasar_varios_parametros.st

PLAYGROUND
|a|
a:=Pruebas new.

a sumar: 2 cac: 3 tumami:4. --->9 "resultado 9" "IMPORTANTE A LA HORA DE LLAMAR PONER MENSAJE Y PARAMETRO IGUAL AL DEL METOD"


METODO
sumar: unValor cac: otroValor tumami:tercervalor
	^(unValor + otroValor + tercervalor) 

"Para PEDIR VARIOS PARAMETROS" "mensaje dos ppuntos y parametros"
"mensa1:parametro mensaje2:otro_parametro mensaje3:otro_parametro3 "







